### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by gargroh** [scarf-sh/scarf-js#22]
Hi @aviaviavi scarf is an awesome package, i hope it will be soon widely adapted by os libs.

I am having some questions related to scarf, mainly in context of disabling it for projects :) due to security policies  :-  

1. I have gone through docs and saw scarf can be disabled through packages json, but is there any way  to switch off the same for multiple projects like monoreps etc..

2. Is it possible to have switch based on apps, for eg. say i have lib `LibA` that uses scarf, and this lib is used in `AppA` and `AppB`, can i switch it off for one of them ?

3. Say this the deps tree, LibD -> LibC -> LibB -> LibA -> scarf , and scarf is disabled through package.json in `LibC` will it be disabled for any application which uses `LibD`

**Comment by aviaviavi** [comment]
Hi @gargroh, so glad to hear you like the package!

> I have gone through docs and saw scarf can be disabled through packages json, but is there any way to switch off the same for multiple projects like monoreps etc..

Yes! If scarf-js is disabled at the top level of the project (ie, where you're running `npm install` from), it will be disabled for _all_ dependencies in the dependency tree, as that is interpreted to mean that the end-user wants to fully disable it. Setting the environment variable `SCARF_ANALYTICS=false` will also disable it for the entire monorepo.

> is it possible to have switch based on apps, for eg. say i have lib LibA that uses scarf, and this lib is used in AppA and AppB, can i switch it off for one of them?

Yes! You can set `scarfSettings.enabled = false` in the package.json of `AppA` or `AppB`, and it will only be disabled for that application. If you don't control `AppA` and `AppB`, there is not currently possible to opt out of analytics on one and not the other, but we can add this feature if you need it!

>  Say this the deps tree, LibD -> LibC -> LibB -> LibA -> scarf , and scarf is disabled through package.json in LibC will it be disabled for any application which uses LibD.

Yes! Any intermediate dependency can disable scarf-js for its dependents. In this case, `LibC` can indeed disable analytics for `LibD`. The end-user can override this if they want to explicitly opt-in, by setting `scarfSettings.enabled = true` in their package.json of `LibD`, or via environment variable. 

Hope this answers your questions.

**Comment by gargroh** [comment]
Cool..thanks for description.

**Comment by aviaviavi** [comment]
👍 Closing this, but feel free to reach out with any more questions!
