### ISSUE TITLE
You are need to know IP ...

### ISSUE THREAD

**Issue by furryablack** [scarf-sh/scarf-js#26]
Why?

"Your IP address will be used to look up any available company information"

But it's the lie =)

Pls, explain me, how is it works technically.
How are you to grab a company info with the ip's knowledge?

**Comment by aviaviavi** [comment]
Hi @furryablack. I can assure you it's not a lie :) 

IP addresses are associated with some owning entity. Often this is just the internet service provider, but in many cases, they can be associated with a business or a cloud hosting provider. There are many paid API's which let you look up this information, and we use these API's to learn if the IP is associated with a business. Scarf stores the metadata associated with the IP, but discards the IP address itself from our system. When we find an installation that comes from a business, we show that information to the maintainer of the package.
