### ISSUE TITLE
Respect DO_NOT_TRACK environment variable

### ISSUE THREAD

**Issue by aviaviavi** [scarf-sh/scarf-js#53]
Per https://consoledonottrack.com/, we should respect this standard in addition to our current environment variables

**Comment by lazyfuhrer** [comment]
Hey I'd like to work in this @aviaviavi. you can assign me

**Comment by aviaviavi** [comment]
Awesome, great to have you join us @lazyfuhrer! Don't hesitate to ping us with any questions as you go.
