### ISSUE TITLE
Excluding tests from npm package distribution

### ISSUE THREAD

**Issue by char0n** [scarf-sh/scarf-js#72]
npm package of scarf-js does include `test/*` directory which is intended for development purposes only. It seems to causing issues with yarn + vitest combo. 
 
This was originally reported in https://github.com/swagger-api/swagger-ui/issues/10197. I assume that because of https://github.com/scarf-sh/scarf-js/issues/3, scarf is already disabled, but vitest from whatever reason tries to read tests from the installed scarf.js package.

**Comment by aviaviavi** [comment]
Thanks for reporting @char0n, we will get this fixed ASAP

**Comment by char0n** [comment]
@aviaviavi any ETA on new 1.4.0 release?

**Comment by aviaviavi** [comment]
@char0n it's live as a `next` release! Let us know if you are still seeing issues.

**Comment by char0n** [comment]
@aviaviavi thanks, utilizing 1.4.0 version, will ping if any additional issues.

**Comment by char0n** [comment]
I can confirm that the issue is resolved in v1.4.0 - https://github.com/swagger-api/swagger-ui/issues/10197#issuecomment-2462524442

**Comment by aviaviavi** [comment]
Thanks for the update! We’ll go ahead and tag that release accordingly m.
